### ISSUE TITLE
31-char limit on app title?

### ISSUE THREAD

**Issue by fgmart-zz** [app-inventor-gallery/aig#66] opened 2012-03-18 15:32 UTC
The app title field is limited to 31 characters.

Two comments:
- This seems too short.  I would recommend more... maybe 40 ?
- If you prefer to keep it this short, would you shorten the dialog box that accepts the title to match the limit ?

**Comment by derrell** [comment] 2012-03-18 15:42
The field length limit is actually 30, not 31. This length was selected as "reasonable" and so that the full title fits in the boxes in the home page ribbons.

The dialog box text field size was determined specifically to fit 30 'M's so I believe it is already the correct size.

We can consider a longer max limit, but then we'll have truncation on the home page ribbons, and I felt that was undesirable.

**Comment by fgmart-zz** [comment] 2012-03-18 15:48
Sounds fine to me.  Let's just shorten the title dialog box then?

**Comment by derrell** [comment] 2012-03-18 16:18
But the title dialog box is already the correct size for 30 'M's. For that reason, I don't think it should be shortened.

**Comment by fgmart-zz** [comment] 2012-03-18 16:48
When I type in the Ms, it stops accepting them before I reach the end:

http://www.cs.uml.edu/~fredm/tmp/aicg-title-limit.png

It would be better to have it a bit too small than a bit too large.

**Comment by derrell** [comment] 2012-03-18 18:13
Ok. That was by design to allow for different browsers to have slightly larger font sizes. It's a trivial change to reduce it, though. Let me know what pixel width you'd like for the input field.

**Comment by fgmart-zz** [comment] 2012-03-18 18:29
I'd say about 15%-20% shorter than the existing field.

**Comment by derrell** [comment] 2012-03-18 23:49
Fixed with 2b9c7923a1c69e49db0b4d5544fbb61d570e2043 (not yet live)

**Closed as completed by derrell** 2012-03-18 23:49 UTC
