### ISSUE TITLE
app-specific URLs don't quite work on Ubuntu/Chrome browser

### ISSUE THREAD

**Issue by fgmart-zz** [app-inventor-gallery/aig#74] opened 2012-03-24 19:25 UTC
Paul -- I love all the work you've accomplished.  The per-app URL stuff looks great.

So it totally works on Firefox.

On Chrome browser and Ubuntu, I get the following behavior:
1.  if I paste a valid URL (e.g,. http://app-inventor-gallery.appspot.com/#page%3DApp%26uid%3D21007%26label%3DStar%20Assault) into a new tab, it loads the AIGC home page.
2.  I can then click another app, navigating off the home page -with-an-apps-URL, and go somewhere.
3.  If I hit back, I'll be at the correct page I should have been at (but wasn't) when I started at #1.

I'm running Chrome 16.0.912.77.

Would you check this?  Thank you.

@cpuwhiz11

**Comment by cpuwhiz11** [comment] 2012-03-25 01:14
I can confirm that these issues are happening on the Chrome browser. It also seems to be happening in Internet Explorer. I will look into these issues.

**Comment by derrell** [comment] 2012-03-26 13:18
Should now be fixed in live version.

**Closed as completed by derrell** 2012-03-26 13:18 UTC
